# Generated by Django 4.1.4 on 2023-02-05 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="profil",
            new_name="profile",
        ),
    ]
