# Generated by Django 4.1.4 on 2023-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student_registration_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("First_Name", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
                ("Roll_Number", models.IntegerField(max_length=10)),
                ("Branch", models.CharField(max_length=50)),
                ("Class", models.CharField(max_length=50)),
                ("Student_Image", models.ImageField(upload_to="")),
                ("Mobile", models.CharField(max_length=50)),
                ("Email", models.CharField(max_length=50)),
                ("Last_Name", models.CharField(max_length=50)),
            ],
        ),
    ]
