# Generated by Django 4.1.4 on 2023-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_registration_models",
            name="Student_Image",
        ),
        migrations.AlterField(
            model_name="student_registration_models",
            name="Mobile",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student_registration_models",
            name="Roll_Number",
            field=models.IntegerField(),
        ),
    ]
