# Generated by Django 4.1.4 on 2023-02-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "libraryapp",
            "0002_remove_student_registration_models_student_image_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="student_registration_models",
        ),
    ]
