# Generated by Django 4.1.4 on 2023-02-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraryapp", "0003_delete_student_registration_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="student_registration_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("First_Name", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
                ("Roll_Number", models.IntegerField()),
                ("Branch", models.CharField(max_length=50)),
                ("Class", models.CharField(max_length=50)),
                ("Mobile", models.IntegerField()),
                ("Email", models.CharField(max_length=50)),
                ("Last_Name", models.CharField(max_length=50)),
            ],
        ),
    ]
